version: "3.8"
services:
  traefik:
    image: {{TRAEFIK_IMAGE}}
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - {{TRAEFIK_CONFIG_DIR}}/static/traefik.yml:/etc/traefik/traefik.yml:ro
      - {{TRAEFIK_CONFIG_DIR}}/dynamic:/etc/traefik/dynamic:ro
      - {{TRAEFIK_ACME_DIR}}:/letsencrypt
      - {{TRAEFIK_LOG_DIR}}:/var/log/traefik
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
